/* Simulation code for ADM1_P.Chile_OL_MPC generated by the OpenModelica Compiler OpenModelica v1.21.0 (64-bit). */
#if !defined(ADM1_P_Chile_OL_MPC__MODEL_H)
#define ADM1_P_Chile_OL_MPC__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "ADM1_P.Chile_OL_MPC_functions.h"

#define ADM1__P_Functions_regSign_index 0
#define ADM1__P_Functions_round_index 1
#define Modelica_Blocks_Tables_Internal_getNextTimeEvent_index 2
#define Modelica_Blocks_Tables_Internal_getTimeTableTmax_index 3
#define Modelica_Blocks_Tables_Internal_getTimeTableTmin_index 4
#define Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer_index 5
#define Modelica_Blocks_Types_ExternalCombiTimeTable_constructor_index 6
#define Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_index 7
#define Modelica_Fluid_Utilities_regStep_index 8
#define Modelica_Utilities_Strings_isEmpty_index 9
#define Modelica_Utilities_Strings_length_index 10
#define Modelica_Utilities_Strings_Advanced_skipWhiteSpace_index 11

extern void ADM1_P_Chile_OL_MPC_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void ADM1_P_Chile_OL_MPC_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void ADM1_P_Chile_OL_MPC_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int ADM1_P_Chile_OL_MPC_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_checkForAsserts(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int ADM1_P_Chile_OL_MPC_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* ADM1_P_Chile_OL_MPC_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* ADM1_P_Chile_OL_MPC_relationDescription(int i);
extern void ADM1_P_Chile_OL_MPC_function_initSample(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ADM1_P_Chile_OL_MPC_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ADM1_P_Chile_OL_MPC_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ADM1_P_Chile_OL_MPC_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ADM1_P_Chile_OL_MPC_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ADM1_P_Chile_OL_MPC_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ADM1_P_Chile_OL_MPC_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int ADM1_P_Chile_OL_MPC_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ADM1_P_Chile_OL_MPC_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ADM1_P_Chile_OL_MPC_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ADM1_P_Chile_OL_MPC_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ADM1_P_Chile_OL_MPC_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ADM1_P_Chile_OL_MPC_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int ADM1_P_Chile_OL_MPC_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* ADM1_P_Chile_OL_MPC_linear_model_frame(void);
extern const char* ADM1_P_Chile_OL_MPC_linear_model_datarecovery_frame(void);
extern int ADM1_P_Chile_OL_MPC_mayer(DATA* data, modelica_real** res, short *);
extern int ADM1_P_Chile_OL_MPC_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int ADM1_P_Chile_OL_MPC_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int ADM1_P_Chile_OL_MPC_setInputData(DATA *data, const modelica_boolean file);
extern int ADM1_P_Chile_OL_MPC_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void ADM1_P_Chile_OL_MPC_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void ADM1_P_Chile_OL_MPC_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int ADM1_P_Chile_OL_MPC_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void ADM1_P_Chile_OL_MPC_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void ADM1_P_Chile_OL_MPC_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int ADM1_P_Chile_OL_MPC_inputNames(DATA* data, char ** names);
extern int ADM1_P_Chile_OL_MPC_dataReconciliationInputNames(DATA* data, char ** names);
extern int ADM1_P_Chile_OL_MPC_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int ADM1_P_Chile_OL_MPC_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int ADM1_P_Chile_OL_MPC_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int ADM1_P_Chile_OL_MPC_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "ADM1_P.Chile_OL_MPC_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(ADM1_P_Chile_OL_MPC__MODEL_H) */


