# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS="-IC:/Users/lenovo/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/C-Sources" -I"C:/Program Files/OpenModelica1.21.0-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.21.0-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=ADM1_P_Chile_OL_MPC -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=13 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS=-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lopenblas -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.21.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.21.0-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.21.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.21.0-64bit/bin" -Wl,-rpath,"C:/Program Files/OpenModelica1.21.0-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lszip -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/lenovo/OneDrive - Politecnico di Milano/Work_cloud/DOTTORATO/Sperimentazione MPC/NMPC/Real_old/Real_offline"
MAINFILE=ADM1_P.Chile_OL_MPC.c
MAINOBJ=ADM1_P.Chile_OL_MPC.o
CFILES=ADM1_P.Chile_OL_MPC_functions.c ADM1_P.Chile_OL_MPC_records.c \
ADM1_P.Chile_OL_MPC_01exo.c ADM1_P.Chile_OL_MPC_02nls.c ADM1_P.Chile_OL_MPC_03lsy.c ADM1_P.Chile_OL_MPC_04set.c ADM1_P.Chile_OL_MPC_05evt.c ADM1_P.Chile_OL_MPC_06inz.c ADM1_P.Chile_OL_MPC_07dly.c \
ADM1_P.Chile_OL_MPC_08bnd.c ADM1_P.Chile_OL_MPC_09alg.c ADM1_P.Chile_OL_MPC_10asr.c ADM1_P.Chile_OL_MPC_11mix.c ADM1_P.Chile_OL_MPC_12jac.c ADM1_P.Chile_OL_MPC_13opt.c ADM1_P.Chile_OL_MPC_14lnz.c \
ADM1_P.Chile_OL_MPC_15syn.c ADM1_P.Chile_OL_MPC_16dae.c ADM1_P.Chile_OL_MPC_17inl.c ADM1_P.Chile_OL_MPC_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) ADM1_P.Chile_OL_MPC.makefile ADM1_P.Chile_OL_MPC_literals.h ADM1_P.Chile_OL_MPC_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that ADM1_P.Chile_OL_MPC_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) ADM1_P.Chile_OL_MPC_functions.h ADM1_P.Chile_OL_MPC_literals.h $(OFILES)
	$(CC) -I. -o ADM1_P.Chile_OL_MPC$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)  "-LC:/Program Files/OpenModelica1.21.0-64bit/bin/" "-LC:/Program Files/OpenModelica1.21.0-64bit/lib//omc" "-LC:/Program Files/OpenModelica1.21.0-64bit/lib/" "-LC:/Users/lenovo/AppData/Roaming/.openmodelica/binaries/Modelica" "-LC:/Users/lenovo/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/mingw64" "-LC:/Users/lenovo/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library/win64" "-LC:/Users/lenovo/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Library" -lModelicaExternalC -lModelicaStandardTables -lModelicaIO -lModelicaMatIO -lzlib $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f ADM1_P.Chile_OL_MPC_records.o $(MAINOBJ)

bundle:
	@tar -cvf ADM1_P.Chile_OL_MPC_Files.tar $(GENERATEDFILES)